train:
  batch_size: 16
  num_epochs: 100
  learning_rate: 0.00002
  weight_decay: 0.01
  early_stopping: True
  early_stopping_patience: 20
  cross_validation: True
  cross_validation_folds: 5
  weighted_sampling: False

model:
  pooling: 'mean' # 'mean', 'cls'
  n_layers: 1
  dropout: 0.3
  hidden_size: 768
  intermediate_size: 3072
  n_heads: 12
  num_classes: 1
  hidden_mlp_size: 256
  textual_model: 'distil'
  audio_model: 'wav2vec2'
  pauses: True
  fusion: 'crossgated'
  use_acoustic_features: True
  num_acoustic_features: 55
  af_hidden_size: 128
  af_nheads: 4

data:
  train_dir: "/home/usuaris/veussd/roger.esteve.sanchez/WAB_samples"
  root_text_path: "/home/usuaris/veussd/roger.esteve.sanchez/WAB_samples/text/"
  root_audio_path: "/home/usuaris/veussd/roger.esteve.sanchez/WAB_samples/"
  csv_labels_path: "/home/usuaris/veussd/roger.esteve.sanchez/WAB_samples/labels.csv"
  acoustic_features_path: "/home/usuaris/veussd/roger.esteve.sanchez/WAB_samples/acoustic_features.csv"
  splits_path: "/home/usuaris/veussd/roger.esteve.sanchez/WAB_samples/splits_amyloid/"

wandb:
  project: "CogniAligned-Amyloid"
  entity: ""  # Optional W&B entity/team name
  mode: "online"  # online, offline, disabled

model_name: ''